### ISSUE TITLE
Opening fails with errors on windows

### ISSUE THREAD

**Issue by TomJB1** [samurai-ide/samurai-ide#9]
After following the install instructions in the README I get the following errors and it doesn't start:

Traceback (most recent call last):
  File "C:\Users\tomjb\Documents\repos\samurai-ide\samurai-ide.py", line 31, in <module>
    samurai_ide.setup_and_run()
  File "C:\Users\tomjb\Documents\repos\samurai-ide\samurai_ide\__init__.py", line 68, in setup_and_run
    core.run_ninja()
  File "C:\Users\tomjb\Documents\repos\samurai-ide\samurai_ide\core\core.py", line 73, in run_ninja
    gui.start_ide(app, filenames, projects_path, extra_plugins, linenos)
  File "C:\Users\tomjb\Documents\repos\samurai-ide\samurai_ide\gui\__init__.py", line 100, in start_ide
    import samurai_ide.gui.tools_dock.console_widget  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomjb\Documents\repos\samurai-ide\samurai_ide\gui\tools_dock\console_widget.py", line 332, in <module>
    ConsoleWidget()
  File "C:\Users\tomjb\Documents\repos\samurai-ide\samurai_ide\gui\tools_dock\console_widget.py", line 139, in __init__
    syntax = highlighter.build_highlighter(language='python')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomjb\Documents\repos\samurai-ide\samurai_ide\gui\editor\highlighter.py", line 319, in build_highlighter
    scanners[name] = Scanner(scanner.get("tokens"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomjb\Documents\repos\samurai-ide\samurai_ide\gui\editor\highlighter.py", line 181, in __init__
    self.search = re.compile(pat).search
                  ^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\re\__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\re\_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 815 (line 1, column 816)

**Comment by TomJB1** [comment]
Looks like it could be something to do with changes to regex in more recent python versions. The errors coming from here:
https://github.com/samurai-ide/samurai-ide/blob/f10bb56a2d664417e7fed22a4bb1ff06f2f7fb42/samurai_ide/gui/editor/highlighter.py#L159-L181C45
however it might be present in other places as well.
